#!/usr/bin/env bash

echo "Vérification avant commit..."

find . -name "*.php" \
  -not -path "./data/*" \
  -not -path "./vendor/*" \
  -print0 | xargs -0 -n1 php -l

if git diff --cached --name-only | grep -E '\.(sqlite|db)$'; then
  echo "Erreur : ne committez pas de base SQLite."
  exit 1
fi

echo "OK"