# ./.github/workflows/cd.yml

name: Deploiement FTP

on:
  push:
    branches:
      - main # si on push sur main (ex : lors d'un merge)

jobs:
  deploy:
    runs-on: ubuntu-latest

    steps:
      - name: Récupérer le code
        uses: actions/checkout@v4

      - name: Vérifier la syntaxe PHP
        run: find . -name "*.php" -not -path "./vendor/*" -print0 | xargs -0 -r -n1 php -l

      - name: Déployer par FTPS
        uses: SamKirkland/FTP-Deploy-Action@v4.3.5
        with:
          server: ${{ secrets.FTP_HOST }} # hote FTP en GitHub Secrets
          username: ${{ secrets.FTP_USER }} # user FTP en GitHub Secrets
          password: ${{ secrets.FTP_PWD }} # mot de passe FTP en GitHub Secrets
          protocol: ftps # préférer ftps à ftp si disponible
          local-dir: ./
          server-dir: ./ # chemin vu depuis la racine du compte FTP
          exclude: |
            - **/.git*
            - **/.git*/**
            - **/.github/**
            - **/.githooks/**
            - **/data/**
            - **/*.sqlite
            - **/.env
            - **/node_modules/**