# ./.github/workflows/ci.yml

name: Vérifications # Nom dans l’onglet actions de GitHub

on: # Déclencheurs
  push: # GitHub lance le workflow quand il y a un push
  pull_request: # ou quand une PR est créée / mise à jour

jobs:
  checks: # Un workflow contient des jobs. Ici le job s’appelle checks.
    runs-on: ubuntu-latest # GitHub lance le job sur un runner Ubuntu fourni par GitHub.
    steps: # Les steps sont les étapes à exécuter.
      # Chaque commande exécutée dans un run: renvoie un résultat invisible mais standard : 0 = succès autre chose que 0 = erreur
      - uses: actions/checkout@v4 # récupère le code du dépôt dans le runner, sinon il n’a pas vos fichiers
      - run: echo "Vérifications du projet" # on affiche un message en log
      - run: find . -name "*.php" -not -path "./vendor/*" -print0 | xargs -0 -r -n1 php -l # on verifie la syntaxe php